# Uncomment this line to define a global platform for your project
platform :ios, '8.0'


target 'GRoute' do
	# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  	use_frameworks!
  	
    #pod 'Alamofire', '~> 4.4'

end
